'use strict';
/* P2-A3 candidate review UI - browser download of generated Workbook bytes.
 *
 * The only path from generated bytes to disk: ArrayBuffer/Uint8Array -> Blob ->
 * URL.createObjectURL() -> a synthetic <a download> click -> URL.revokeObjectURL(). No File
 * System Access API, no server round-trip, no console output of the object URL (an object URL is
 * not secret, but logging it is pure debt with no purpose here).
 */
(function (root, factory) {
  const api = factory();
  if (root) root.P2A3WorkbookDownload = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {

  function downloadBytes(bytes, fileName) {
    const blob = new Blob([bytes], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
    const url = URL.createObjectURL(blob);
    try {
      const a = document.createElement('a');
      a.href = url;
      a.download = fileName;
      a.style.display = 'none';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
    } finally {
      // Give the click a tick to start the download before the URL is invalidated.
      setTimeout(() => URL.revokeObjectURL(url), 0);
    }
  }

  return { downloadBytes };
});
